### ISSUE TITLE
Potential for compiled matlab version

### ISSUE THREAD

**Issue by DanNBullock** [drombas/retimat#12]
Hi David,

Great to see this package to come together, I'm thinking I may use it to replace an old, hacky toolkit that I'd made previously for similar applications ([OCT_scripts](https://github.com/DanNBullock/OCT_scripts/tree/master)).  However, I don't currently have access to a matlab instance / license.  Is there a way to produce a [compiled version](https://www.mathworks.com/products/compiler.html) so that the `retimat` toolkit can be used without a specific matlab instance?  Using compiled versions of toolkits / code is how brainlife [addressed this same issue](https://brainlife.io/docs/apps/container/#compiling-matlab-scripts) with running matlab code in docker containers.

**Comment by drombas** [comment]
Hi @DanNBullock!

Are you interested in using specific functions or do you want a single script that processes an image?

I imagine the latter to be easier but I will check what alternatives are out there.
